from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('aboutus/', views.aboutus_view, name='aboutus'),
    path('aboutzanzibar/', views.aboutzanzibar_view, name='aboutzanzibar'),
    path('contact/', views.contact_view, name='contact'),
    path('packages/', views.packages_view, name='packages'),
    path('gallery/', views.gallery_view, name='gallery'),
    path('hotel/', views.hotel_view, name='hotel'),
    path('safari/', views.safari_view, name='safari'),
    path('transport/', views.transport_view, name='transport'),
    path('book/', views.book_view, name='book'),
    path('admin-login/', views.admin_login_view, name='admin_login'),
    path('admin-signup/', views.admin_signup_view, name='admin_signup'),
    path('admin-logout/', views.admin_logout_view, name='admin_logout'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-dashboard/users/add/', views.add_dashboard_user, name='add_dashboard_user'),
    path('admin-dashboard/posts/add/', views.add_post, name='add_post'),
    path('admin-dashboard/posts/<int:post_id>/edit/', views.edit_post, name='edit_post'),
    path('admin-dashboard/posts/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('admin-dashboard/packages/add/', views.add_package, name='add_package'),
    path('admin-dashboard/packages/<int:package_id>/edit/', views.edit_package, name='edit_package'),
    path('admin-dashboard/packages/<int:package_id>/delete/', views.delete_package, name='delete_package'),
    path('admin-dashboard/hotels/add/', views.add_hotel, name='add_hotel'),
    path('admin-dashboard/hotels/<int:hotel_id>/edit/', views.edit_hotel, name='edit_hotel'),
    path('admin-dashboard/hotels/<int:hotel_id>/delete/', views.delete_hotel, name='delete_hotel'),
    path('admin-dashboard/safaris/add/', views.add_safari, name='add_safari'),
    path('admin-dashboard/safaris/<int:safari_id>/edit/', views.edit_safari, name='edit_safari'),
    path('admin-dashboard/safaris/<int:safari_id>/delete/', views.delete_safari, name='delete_safari'),
    path('admin-dashboard/transports/add/', views.add_transport, name='add_transport'),
    path('admin-dashboard/transports/<int:transport_id>/edit/', views.edit_transport, name='edit_transport'),
    path('admin-dashboard/transports/<int:transport_id>/delete/', views.delete_transport, name='delete_transport'),
    path('admin-dashboard/bookings/<int:booking_id>/status/', views.update_booking_status, name='update_booking_status'),
    path('admin-dashboard/inquiries/<int:inquiry_id>/status/', views.update_inquiry_status, name='update_inquiry_status'),
    path('admin-dashboard/bookings/<int:booking_id>/delete/', views.delete_booking, name='delete_booking'),
    path('admin-dashboard/inquiries/<int:inquiry_id>/delete/', views.delete_inquiry, name='delete_inquiry'),
    path('admin-dashboard/bookings/<int:booking_id>/restore/', views.restore_booking, name='restore_booking'),
    path('admin-dashboard/inquiries/<int:inquiry_id>/restore/', views.restore_inquiry, name='restore_inquiry'),
    path('admin-dashboard/bookings/export/', views.export_bookings_csv, name='export_bookings_csv'),
    path('admin-dashboard/inquiries/export/', views.export_inquiries_csv, name='export_inquiries_csv'),
]
