# Generated by Django 4.2.24 on 2025-09-30 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_page', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.RemoveField(
            model_name='safari',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='safari',
            name='image',
        ),
        migrations.RemoveField(
            model_name='safari',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='image',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='safari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.safari'),
        ),
        migrations.AddField(
            model_name='booking',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.transport'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='safari',
            name='location',
            field=models.CharField(default='Zanzibar', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safari',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='safari',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transport',
            name='name',
            field=models.CharField(default='Zanzibar', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='transport',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.package'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='0000000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transport',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(help_text='Vehicle type e.g. Land Cruiser, Minivan', max_length=100),
        ),
    ]
