# Generated by Django 4.2.29 on 2026-03-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_booking_service_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safari',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
