# Generated by Django 4.2.29 on 2026-03-31 17:29

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_hotel_archived_at_package_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpost',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-booking_date', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='safari',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='adminpost',
            name='target_page',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('resolved', 'Resolved')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='safari',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='safari',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transport',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
